### ISSUE TITLE
[BUG] escaping appeared with starship

### ISSUE THREAD

**Issue by sharpchen** [akinsho/toggleterm.nvim#615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Inside toggleterm
![image](https://github.com/user-attachments/assets/ebf3929f-6fd5-4689-86e2-32b16b0f9faa)

### Expected Behavior

In normal terminal
![image](https://github.com/user-attachments/assets/0e635676-bed4-493d-a0f1-2bc3dde1158c)

### Steps To Reproduce

<details>
<summary>starship config</summary>

```toml
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = '$all'

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]

[directory]
truncation_length = 3

[dotnet]
symbol = ' '
format = '[$symbol($version )($tfm)]($style)'

[env_var]
disabled = true

[elm]
symbol = " "

[git_branch]

[git_commit]
disabled = false
commit_hash_length = 4
tag_disabled = false

[git_state]
disabled = true

[git_status]

[golang]
symbol = "󰟓 "

[kubernetes]
symbol = "⎈ "

[line_break]
disabled = false

[memory_usage]
disabled = true

[java]
symbol = " "

[julia]
symbol = " "

[nodejs]
symbol = ""

[package]
symbol = "📦"

[rust]
symbol = '󱘗'

[time]
disabled = true

[username]
disabled = false
```

</details>

<details>
<summary>toggleterm config</summary>

```lua
return {
  'akinsho/toggleterm.nvim',
  version = '*',
  init = function() end,
  config = function()
    vim.o.shell = vim
      .iter({ 'bash', 'nu', 'pwsh', 'zsh' })
      :filter(function(x)
        return vim.fn.executable(x) == 1
      end)
      :peek()
    require('toggleterm').setup({
      start_in_insert = true,
      direction = 'float',
      float_opts = {
        border = 'rounded',
      },
    })

    local Terminal = require('toggleterm.terminal').Terminal
    local rootTerm = Terminal:new({ count = 1 })
    local bufTerm = Terminal:new({ count = 5 })
    local bufPath = nil
    vim.keymap.set({ 'n', 'x', 't', 'v' }, '<C-\\>', function()
      rootTerm:toggle()
    end)
    vim.keymap.set({ 'n', 'x', 't', 'v' }, '<M-\\>', function()
      ---@type string
      local path = require('plenary.path'):new({ vim.api.nvim_buf_get_name(0) }):parent().filename
      if vim.fn.isdirectory(path) == 1 then
        local path_changed = path ~= bufPath
        bufPath = path_changed and path or bufPath
        if path_changed then
          if not bufTerm:is_open() then
            bufTerm:toggle()
            bufTerm:toggle()
          end
          if vim.o.shell == 'bash' then
            bufTerm:send({ ("cd '%s'; history -d $(history 1)"):format(path), 'clear; history -d $(history 1)' })
          else
            bufTerm:send({ ("cd '%s'"):format(path), vim.o.shell == 'pwsh' and 'cls' or 'clear' })
          end
        end
      end
      bufTerm:toggle()
      if vim.fn.mode() == 'n' and vim.o.filetype == 'toggleterm' then
        vim.cmd('execute "normal! i"')
      end
    end)
    vim.api.nvim_create_autocmd({ 'TermEnter' }, {
      callback = function()
        for _, buffers in ipairs(vim.fn.getbufinfo()) do
          local filetype = vim.api.nvim_buf_get_option(buffers.bufnr, 'filetype')
          if filetype == 'toggleterm' then
            vim.api.nvim_create_autocmd({ 'BufWriteCmd', 'FileWriteCmd', 'FileAppendCmd' }, {
              buffer = buffers.bufnr,
              command = 'q!',
            })
          end
        end
      end,
    })
  end,
}
```

<details>

### Environment

```Markdown
- OS: ArchWSL

{
  machine = "x86_64",
  release = "5.15.153.1-microsoft-standard-WSL2",
  sysname = "Linux",
  version = "#1 SMP Fri Mar 29 23:14:13 UTC 2024"
}

- neovim version: NVIM v0.10.1
- Shell: bash
```
